language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools

    # The BuildTools version used by your project
    - build-tools-21.1.2

    # The SDK version used to compile your project
    - android-22 
	
before_install:
- chmod +x gradlew
-android update sdk --filter extra-android-support --no-ui --force > /dev/null
-android update sdk --filter extra-android-m2repository --no-ui --force > /dev/null 